baseURL = 'https://zu00423828.github.io/'
languageCode = 'en-us'
title = 'FongYuan Note'

theme = "hugo-theme-stack"


[Params.colorScheme]
  toggle =false
  default="dark" 


[[menu.main]]
  name = "Hugo 指令"
  weight = 1
  url  = "/posts/"

[[menu.main]]
  name = "Linux"
  weight = 1
  url  = "/linux/"